### ISSUE TITLE
which one is original?

### ISSUE THREAD

**Issue by raymond-yiqunwang** [gdroguski/GaussianProcesses#2]
Check it out if you haven't seen this.

https://www.cs.ubc.ca/~nando/540-2013/projects/p5.pdf

**Comment by gdroguski** [comment]
Thanks, it was one of the few papers/docs which were my inspiration. Wanted to replicate or get similar results on different data ;)

**Comment by hlgohgpjh** [comment]
Why I download some new data form Yahoo and put them into "Data" file, while the python said [Errno 2] No such file or directory: 'Data/.csv' ?
